[workspace]
members = [
    "dailyprogrammer",
    "hackerrank/algorithms",
    "sorts",
    "facebook",
    "leetcode",
    "google",
    "shuffle",
    "pathfinding",
    "euler",
    "misc",
    "exercism",
]